replicaCount: 1

image:
  repository: ghcr.io/soul-research-labs/escanorr
  pullPolicy: IfNotPresent
  tag: "" # defaults to Chart.appVersion

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

env:
  RUST_LOG: "info,escanorr=debug"
  ESCANORR_HOST: "0.0.0.0"
  ESCANORR_PORT: "3000"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "2000m"

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}
